In [2]:
# exploring four datasets given...

In [13]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [14]:
data_dir = Path("datasets")

In [15]:
customers = pd.read_csv(data_dir / "customers.csv")
order_items = pd.read_csv(data_dir / "order_items.csv")
orders = pd.read_csv(data_dir / "orders.csv")
products = pd.read_csv(data_dir / "products.csv")

In [19]:
print("Customers:\n")
display(customers.head())
print("order_items:\n")
display(order_items.head())
print("orders:\n")
display(orders.head())
print("Products:\n")
display(products.head())

Customers:

   customer_id signup_date state acquisition_channel
0            1  2024-09-13    CO      organic_search
1            2  2025-10-21    IL         paid_search
2            3  2025-01-17    AZ            referral
3            4  2024-06-23    FL         paid_social
4            5  2025-04-08    IL         paid_social

order_items:

   order_id  product_id  quantity  unit_price  discount_amount
0    100001        1031         1       38.99              0.0
1    100002        1087         1       45.99              0.0
2    100002        1072         1      141.99              0.0
3    100003        1048         1      139.99              0.0
4    100004        1083         1       19.99              2.0

orders:

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
0,100001,1530,2024-01-01 09:24:45,completed,credit_card,NaN,6.95
1,100002,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00
2,100003,840,2024-01-01 10:59:09,completed,credit_card,NaN,0.00
3,100004,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00
4,100005,3452,2024-01-01 17:44:03,completed,gift_card,NaN,0.00

Products:

   product_id            product_name  category  list_price  unit_cost
0        1001        Brass Chef Knife   Kitchen       61.99      38.13
1        1002    Walnut Cutting Board   Kitchen      138.99      74.76
2        1003  Matte Black Dutch Oven   Kitchen       22.99      13.50
3        1004         Classic Skillet   Kitchen       75.99      39.86
4        1005   Linen Mixing Bowl Set  Kitchen        79.99      41.11

In [20]:
customers.info()
order_items.info()
orders.info()
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3600 non-null   int64
 1   signup_date          3600 non-null   str
 2   state                3600 non-null   str
 3   acquisition_channel  3600 non-null   str
dtypes: int64(1), str(3)
memory usage: 112.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 15608 entries, 0 to 15607
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         15608 non-null  int64
 1   product_id       15608 non-null  int64
 2   quantity         15608 non-null  int64
 3   unit_price       15409 non-null  float64
 4   discount_amount  15608 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 609.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 9245 entries, 0 to 9244
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        9245 non-null   int64
 1   customer_id     9245 non-null   int64
 2   order_date      9245 non-null   str
 3   status          9245 non-null   str
 4   payment_method  9245 non-null   str
 5   discount_code   1411 non-null   str
 6   shipping_fee    9245 non-null   float64
dtypes: float64(1), int64(2), str(4)
memory usage: 505.7 KB
<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    90 non-null     int64
 1   product_name  90 non-null     str
 2   category      90 non-null     str
 3   list_price    90 non-null     float64
 4   unit_cost     90 non-null     float64
dtypes: float64(2), int64(1), str(2)
memory usage: 3.6 KB

In [21]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
}

for name, df in datasets.items():
    print(f"\n--- {name} ---")
    print("Shape:", df.shape)
    print("\nData types:")
    print(df.dtypes)
    print("\nMissing values:")
    print(df.isna().sum())
    print("\nDuplicate rows:", df.duplicated().sum())
    print("\nSummary:")
    display(df.describe(include="all").T)

--- customers ---
Shape: (3600, 4)

Data types:
customer_id            int64
signup_date              str
state                    str
acquisition_channel      str
dtype: object

Missing values:
customer_id            0
signup_date            0
state                  0
acquisition_channel    0
dtype: int64

Duplicate rows: 0

Summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,3600.0,NaN,NaN,NaN,1800.5,1039.374812,1.0,900.75,1800.5,2700.25,3600.0
signup_date,3600,811,2025-10-29,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state,3600,35,CA,451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acquisition_channel,3600,6,organic_search,1230,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- orders ---
Shape: (9245, 7)

Data types:
order_id            int64
customer_id         int64
order_date            str
status                str
payment_method        str
discount_code         str
shipping_fee      float64
dtype: object

Missing values:
order_id             0
customer_id          0
order_date           0
status               0
payment_method       0
discount_code     7834
shipping_fee         0
dtype: int64

Duplicate rows: 38

Summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,9245.0,NaN,NaN,NaN,104604.530882,2657.471479,100001.0,102304.0,104605.0,106907.0,109207.0
customer_id,9245.0,NaN,NaN,NaN,1784.05484,1062.469902,2.0,863.0,1786.0,2738.0,3600.0
order_date,9245,9206,2024-01-06 16:37:36,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status,9245,3,completed,8490,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_method,9245,4,credit_card,5332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
discount_code,1411,3,HOLIDAY20,782,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipping_fee,9245.0,NaN,NaN,NaN,1.544862,2.889826,0.0,0.0,0.0,0.0,6.95

--- order_items ---
Shape: (15608, 5)

Data types:
order_id             int64
product_id           int64
quantity             int64
unit_price         float64
discount_amount    float64
dtype: object

Missing values:
order_id             0
product_id           0
quantity             0
unit_price         199
discount_amount      0
dtype: int64

Duplicate rows: 0

Summary:

,count,mean,std,min,25%,50%,75%,max
order_id,15608.0,104570.429011,2659.674531,100001.00,102269.75,104554.50,106867.25,109207.00
product_id,15608.0,1046.471040,28.278148,1001.00,1020.00,1048.00,1073.00,1090.00
quantity,15608.0,1.244810,0.577641,1.00,1.00,1.00,1.00,4.00
unit_price,15409.0,113.084088,108.590935,7.99,49.99,86.09,141.74,812.69
discount_amount,15608.0,3.201492,11.154638,0.00,0.00,0.00,0.00,196.56

--- products ---
Shape: (90, 5)

Data types:
product_id        int64
product_name        str
category            str
list_price      float64
unit_cost       float64
dtype: object

Missing values:
product_id      0
product_name    0
category        0
list_price      0
unit_cost       0
dtype: int64

Duplicate rows: 0

Summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
product_id,90.0,NaN,NaN,NaN,1045.5,26.124701,1001.0,1023.25,1045.5,1067.75,1090.0
product_name,90,90,Brass Chef Knife,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
category,90,24,Kitchen,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
list_price,90.0,NaN,NaN,NaN,134.378889,136.899512,7.99,52.49,95.49,151.49,773.99
unit_cost,90.0,NaN,NaN,NaN,69.563222,76.82018,4.76,24.5475,49.275,74.33,445.47

In [25]:
# In table "orders" --- discount_code = 7834 missing
#order_items --- unit_price = 199 missing
customers[customers.duplicated(keep=False)]
order_items[order_items.duplicated(keep=False)]
orders[orders.duplicated(keep=False)]

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
47,100048,3320,2024-01-06 16:37:36,completed,credit_card,NaN,6.95
130,107012,870,2025-08-12 10:39:49,completed,apple_pay,NaN,0.00
303,100303,853,2024-02-03 08:33:22,completed,apple_pay,NaN,0.00
310,106199,3072,2025-06-09 23:50:03,completed,credit_card,NaN,6.95
479,104695,443,2025-02-14 11:56:23,completed,credit_card,NaN,0.00
...,...,...,...,...,...,...,...
8737,107493,1664,2025-09-21 23:42:50,completed,apple_pay,NaN,6.95
9032,102517,1254,2024-08-28 20:08:41,completed,paypal,NaN,0.00
9104,109068,1981,2025-12-20 13:27:25,completed,credit_card,HOLIDAY20,6.95
9122,108138,1241,2025-11-07 12:15:41,returned,gift_card,NaN,0.00
9124,109087,3358,2025-12-22 08:35:44,completed,credit_card,HOLIDAY20,0.00

In [26]:
duplicate_mask = orders.duplicated(
    subset=["order_id", "customer_id", "order_date"],
    keep=False
)

orders.loc[duplicate_mask].sort_values(
    ["order_id", "customer_id", "order_date"]
)

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
47,100048,3320,2024-01-06 16:37:36,completed,credit_card,NaN,6.95
8560,100048,3320,2024-01-06 16:37:36,completed,credit_card,NaN,6.95
303,100303,853,2024-02-03 08:33:22,completed,apple_pay,NaN,0.00
7556,100303,853,2024-02-03 08:33:22,completed,apple_pay,NaN,0.00
712,100710,526,2024-03-13 13:39:17,completed,credit_card,NaN,0.00
...,...,...,...,...,...,...,...
8698,108585,1995,2025-11-28 12:43:37,completed,apple_pay,HOLIDAY20,0.00
3104,109068,1981,2025-12-20 13:27:25,completed,credit_card,HOLIDAY20,6.95
9104,109068,1981,2025-12-20 13:27:25,completed,credit_card,HOLIDAY20,6.95
4213,109087,3358,2025-12-22 08:35:44,completed,credit_card,HOLIDAY20,0.00
9124,109087,3358,2025-12-22 08:35:44,completed,credit_card,HOLIDAY20,0.00

orders = orders.drop_duplicates(
    subset=["order_id", "customer_id", "order_date"],
    keep="first"
).copy()

In [27]:
orders["discount_code"] = orders["discount_code"].fillna("No code")

In [28]:
missing_prices = order_items[order_items["unit_price"].isna()].merge(
    products[["product_id", "product_name", "list_price"]],
    on="product_id",
    how="left"
)

display(missing_prices.head(20))

,order_id,product_id,quantity,unit_price,discount_amount,product_name,list_price
0,100033,1086,1,NaN,0.00,Modern Under Bed Bin,97.99
1,100062,1020,1,NaN,0.00,Coastal Weighted Blanket,54.99
2,100116,1087,2,NaN,0.00,Cotton Pantry Container Set,45.99
3,100210,1014,1,NaN,0.00,Matte Black Stock Pot,36.99
4,100361,1077,1,NaN,0.00,Classic Table Runner,25.99
5,100396,1015,1,NaN,0.00,Oak Measuring Cup Set,96.99
6,100468,1004,2,NaN,0.00,Classic Skillet,75.99
7,100545,1090,2,NaN,0.00,Bamboo Laundry Basket,17.99
8,100573,1090,1,NaN,0.00,Bamboo Laundry Basket,17.99
9,100639,1087,2,NaN,0.00,Cotton Pantry Container Set,45.99
10,100664,1037,1,NaN,4.35,Coastal Waffle Towel Set,28.99
11,100834,1041,1,NaN,0.00,Nordic Side Table,553.99
12,100869,1085,1,NaN,17.40,Coastal Closet System,115.99
13,100891,1002,1,NaN,0.00,Walnut Cutting Board,138.99
14,100968,1069,1,NaN,4.05,Bamboo Umbrella Stand,26.99
15,100996,1027,2,NaN,0.00,Walnut Down Pillow,90.99
16,101082,1028,1,NaN,0.00,Brass Towel Set,77.99
17,101111,1078,1,NaN,0.00,Nordic Ornament Set,85.99
18,101116,1026,1,NaN,0.00,Cotton Linen Sheet Set,161.99
19,101148,1070,1,NaN,18.45,Stoneware Wall Mirror,122.99